name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build & Test

    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.15.4"
          otp-version: "26.0.2"

      - name: Retrieve Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ hashFiles('mix.lock') }}-v1

      - name: Install Mix Dependencies
        run: mix deps.get

      - name: Compile Mix Dependencies
        run: mix deps.compile

      - name: Run Tests
        run: mix ci
